=== 01QueN10/EnderIO/resources/assets/enderio/config/recipes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://enderio.com/recipes"
  elementFormDefault="unqualified" attributeFormDefault="unqualified"
  xmlns="http://www.w3.org/2001/XMLSchema" xmlns:enderio="http://enderio.com/recipes">




  <element name="recipes">


    <complexType>
      <sequence maxOccurs="unbounded" minOccurs="0">
        <choice maxOccurs="1" minOccurs="1">
          <element name="alias">
            <complexType>
              <sequence>
                <element minOccurs="0" maxOccurs="unbounded"
                  name="config">
                  <complexType>
                    <attribute use="required" name="section"
                      type="string"></attribute>
                    <attribute use="required" name="name"
                      type="string"></attribute>
                    <attribute use="optional" name="value"
                      type="boolean"></attribute>
                  </complexType>
                </element>
                <element minOccurs="0" maxOccurs="unbounded"
                  name="dependency">
                  <complexType>
                    <attribute use="required" name="item"
                      type="string"></attribute>
                    <attribute use="optional" name="reverse"
                      type="boolean"></attribute>
                  </complexType>
                </element>
                <element minOccurs="0" maxOccurs="1" name="level">
                  <complexType>
                    <attribute use="optional" name="minlevel"
                      type="int"></attribute>
                    <attribute use="optional" name="maxlevel"
                      type="int"></attribute>
                  </complexType>
                </element>
              </sequence>
              <attribute name="name" type="string" use="required"></attribute>
              <attribute name="item" type="string" use="required"></attribute>
            </complexType>
          </element>
          <element name="recipe">
            <complexType>
              <sequence>
                <element minOccurs="0" maxOccurs="unbounded"
                  name="config">
                  <complexType>
                    <attribute use="required" name="section"
                      type="string"></attribute>
                    <attribute use="required" name="name"
                      type="string"></attribute>
                    <attribute use="optional" name="value"
                      type="boolean"></attribute>
                  </complexType>
                </element>
                <element minOccurs="0" maxOccurs="unbounded"
                  name="dependency">
                  <complexType>
                    <attribute use="required" name="item"
                      type="string"></attribute>
                    <attribute use="optional" name="reverse"
                      type="boolean"></attribute>
                  </complexType>
                </element>
                <element minOccurs="0" maxOccurs="1" name="level">
                  <complexType>
                    <attribute use="optional" name="minlevel"
                      type="int"></attribute>
                    <attribute use="optional" name="maxlevel"
                      type="int"></attribute>
                  </complexType>
                </element>
                <choice minOccurs="1" maxOccurs="1">
                  <element minOccurs="1" maxOccurs="unbounded"
                    name="crafting">
                    <complexType>
                      <sequence>
                        <element minOccurs="0" maxOccurs="unbounded"
                          name="config">
                          <complexType>
                            <attribute use="required" name="section"
                              type="string"></attribute>
                            <attribute use="required" name="name"
                              type="string"></attribute>
                            <attribute use="optional" name="value"
                              type="boolean"></attribute>
                          </complexType>
                        </element>
                        <element minOccurs="0" maxOccurs="unbounded"
                          name="dependency">
                          <complexType>
                            <attribute use="required" name="item"
                              type="string"></attribute>
                            <attribute use="optional" name="reverse"
                              type="boolean"></attribute>
                          </complexType>
                        </element>
                        <element minOccurs="0" maxOccurs="unbounded"
                          name="level">
                          <complexType>
                            <attribute use="optional" name="minlevel"
                              type="int"></attribute>
                            <attribute use="optional" name="maxlevel"
                              type="int"></attribute>
                          </complexType>
                        </element>
                        <choice minOccurs="1" maxOccurs="1">
                          <element minOccurs="1" maxOccurs="1"
                            name="grid">
                            <complexType>
                              <sequence>
                                <element minOccurs="1"
                                  maxOccurs="9" name="item">
                                  <complexType>
                                    <attribute use="optional"
                                      name="name" type="string"></attribute>
                                  </complexType>
                                </element>
                              </sequence>
                              <attribute use="optional" name="size">
                                <simpleType>
                                  <restriction base="string">
                                    <length value="3"></length>
                                  </restriction>
                                </simpleType>
                              </attribute>
                            </complexType>
                          </element>
                          <element minOccurs="1" maxOccurs="1"
                            name="shapeless">
                            <complexType>
                              <sequence>
                                <element minOccurs="1"
                                  maxOccurs="9" name="item">
                                  <complexType>
                                    <attribute use="optional"
                                      name="name" type="string"></attribute>
                                  </complexType>
                                </element>
                              </sequence>
                            </complexType>
                          </element>
                        </choice>
                        <element minOccurs="1" maxOccurs="1"
                          name="output">
                          <complexType>
                            <attribute use="required" name="name"
                              type="string"></attribute>
                            <attribute use="optional" name="amount">
                              <simpleType>
                                <restriction base="int">
                                  <minInclusive value="1"></minInclusive>
                                  <maxInclusive value="64"></maxInclusive>
                                </restriction>
                              </simpleType>
                            </attribute>
                          </complexType>
                        </element>
                      </sequence>
                    </complexType>
                  </element>
                  <element minOccurs="1" maxOccurs="unbounded"
                    name="smelting">
                    <complexType>
                      <sequence>
                        <element minOccurs="0" maxOccurs="unbounded"
                          name="config">
                          <complexType>
                            <attribute use="required" name="section"
                              type="string"></attribute>
                            <attribute use="required" name="name"
                              type="string"></attribute>
                            <attribute use="optional" name="value"
                              type="boolean"></attribute>
                          </complexType>
                        </element>
                        <element minOccurs="0" maxOccurs="unbounded"
                          name="dependency">
                          <complexType>
                            <attribute use="required" name="item"
                              type="string"></attribute>
                            <attribute use="optional" name="reverse"
                              type="boolean"></attribute>
                          </complexType>
                        </element>
                        <element minOccurs="0" maxOccurs="unbounded"
                          name="level">
                          <complexType>
                            <attribute use="optional" name="minlevel"
                              type="int"></attribute>
                            <attribute use="optional" name="maxlevel"
                              type="int"></attribute>
                          </complexType>
                        </element>
                        <element minOccurs="1" maxOccurs="1"
                          name="input">
                          <complexType>
                            <attribute use="required" name="name"
                              type="string"></attribute>
                            <attribute use="optional" name="amount">
                              <simpleType>
                                <restriction base="int">
                                  <minInclusive value="1"></minInclusive>
                                  <maxInclusive value="64"></maxInclusive>
                                </restriction>
                              </simpleType>
                            </attribute>
                          </complexType>
                        </element>
                        <element minOccurs="1" maxOccurs="1"
                          name="output">
                          <complexType>
                            <attribute use="required" name="name"
                              type="string"></attribute>
                            <attribute use="optional" name="amount">
                              <simpleType>
                                <restriction base="int">
                                  <minInclusive value="1"></minInclusive>
                                  <maxInclusive value="64"></maxInclusive>
                                </restriction>
                              </simpleType>
                            </attribute>
                          </complexType>
                        </element>
                      </sequence>
                      <attribute use="required" name="exp">
                        <simpleType>
                          <restriction base="float">
                            <minInclusive value="0"></minInclusive>
                            <maxInclusive value="1"></maxInclusive>
                          </restriction>
                        </simpleType>
                      </attribute>
                    </complexType>
                  </element>
                </choice>
              </sequence>
              <attribute use="optional" name="required" type="boolean"></attribute>
              <attribute use="required" name="name" type="string"></attribute>
            </complexType>
          </element>
        </choice>
      </sequence>
    </complexType>
  </element>







</schema>

=== 01QueN10/EnderIO/resources/assets/enderio/config/recipe_aliases_core.xml
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">

<!-- 

These are the build-in aliases. You cannot change this file, it is a
reference for you only and will be generated every time the game starts.

To make changes to the aliases, copy the aliases you want to change to
the matching _user.xml.

Item specifications can reference an alias, an ore dictionary name, a
block or an item. You can force the type by prefixing the value with
"oredict:", "block:" or "item:".

More information on the syntax can be found in the recipes.xsd file. An
XML editor will display that as tooltips when editing this file.

 -->

  <alias name="ZOMBIE_ELECTRODE" item="enderio:item_material:38" />
  <alias name="ZOMBIE_CONTROLLER" item="enderio:item_material:39" />
  <alias name="FRANKEN_ZOMBIE" item="enderio:item_material:40" />
  <alias name="ENDER_RESONATOR" item="enderio:item_material:41" />
  <alias name="SENTIENT_ENDER" item="enderio:item_material:42" />
  <alias name="SKELETAL_CONTRACTOR" item="enderio:item_material:43" />

  <alias name="CAPACITOR1" item="enderio:item_basic_capacitor:0" />
  <alias name="CAPACITOR2" item="enderio:item_basic_capacitor:1" />
  <alias name="CAPACITOR3" item="enderio:item_basic_capacitor:2" />
  
  <alias name="GEAR" item="gearStone" />
  <alias name="CHASSIS" item="itemMachineChassi" />
  
  <alias name="FUSED_QUARTZ" item="oredict:fusedQuartz" />
  <alias name="FUSED_GLASS" item="oredict:fusedGlass" ></alias>
  <alias name="ENLIGHTED_QUARTZ" item="oredict:enlightenedFusedQuartz" />
  <alias name="ENLIGHTED_GLASS" item="oredict:enlightenedFusedGlass" />
  <alias name="DARK_QUARTZ" item="oredict:darkFusedQuartz" />
  <alias name="DARK_GLASS" item="oredict:darkFusedGlass" />

  <alias name="ELECTRICAL_STEEL" item="ingotElectricalSteel" />
  <alias name="ENERGETIC_ALLOY" item="ingotEnergeticAlloy" />
  <alias name="VIBRANT_ALLOY" item="ingotVibrantAlloy" />
  <alias name="REDSTONE_ALLOY" item="ingotRedstoneAlloy" />
  <alias name="CONDUCTIVE_IRON" item="ingotConductiveIron" />
  <alias name="PULSATING_IRON" item="ingotPulsatingIron" />
  <alias name="DARK_STEEL" item="ingotDarkSteel" />
  <alias name="SOULARIUM" item="ingotSoularium" />

  <alias name="ELECTRICAL_STEEL_BLOCK" item="blockElectricalSteel" />
  <alias name="ENERGETIC_ALLOY_BLOCK" item="blockEnergeticAlloy" />
  <alias name="VIBRANT_ALLOY_BLOCK" item="blockVibrantAlloy" />
  <alias name="REDSTONE_ALLOY_BLOCK" item="blockRedstoneAlloy" />
  <alias name="CONDUCTIVE_IRON_BLOCK" item="blockConductiveIron" />
  <alias name="PULSATING_IRON_BLOCK" item="blockPulsatingIron" />
  <alias name="DARK_STEEL_BLOCK" item="blockDarkSteel" />
  <alias name="SOULARIUM_BLOCK" item="blockSoularium" />

  <alias name="SILICON" item="itemSilicon" />
  <alias name="CONDUIT_BINDER" item="itemConduitBinder" />
  <alias name="BINDER_COMPOSITE" item="itemBinderComposite" />
  <alias name="PULSATING_IRON_NUGGET" item="nuggetPulsatingIron" />
  <alias name="VIBRANT_NUGGET" item="nuggetVibrantAlloy" />
  <alias name="PULSATING_CRYSTAL" item="itemPulsatingCrystal" />
  <alias name="VIBRANT_CRYSTAL" item="itemVibrantCrystal" />
  <alias name="DARK_GRINDING_BALL" item="itemDarkGrindingBall" />
  <alias name="ENDER_CRYSTAL" item="itemEnderCrystal" />
  <alias name="ATTRACTOR_CRYSTAL" item="itemAttractorCrystal" />
  <alias name="WEATHER_CRYSTAL" item="itemWeatherCrystal" />
  <alias name="NUTRITIOUS_STICK" item="itemNutritiousStick" />
  <alias name="CHASSIPARTS" item="itemChassiParts" />

  <alias name="CAP_BANK_1" item="enderio:block_cap_bank:1" />
  <alias name="CAP_BANK_2" item="enderio:block_cap_bank:2" />
  <alias name="CAP_BANK_3" item="enderio:block_cap_bank:3" />

  <alias name="SOLAR_1" item="enderio:block_solar_panel:0" />
  <alias name="SOLAR_2" item="enderio:block_solar_panel:1" />
  <alias name="SOLAR_3" item="enderio:block_solar_panel:2" />

  <alias name="CONDUIT_PROBE" item="enderio:item_conduit_probe:0" />

  <alias name="HEAD_ENDERMAN" item="enderio:block_enderman_skull:0" />
  <alias name="HEAD_SKELETON" item="minecraft:skull:0" />
  <alias name="HEAD_CREEPER" item="minecraft:skull:2" />
  <alias name="HEAD_ZOMBIE" item="minecraft:skull:4" />

  <alias name="HEAD_ENDERMAN_TORMENTED" item="enderio:block_enderman_skull:2" />

  <alias name="LIGHT_ELECTRIC" item="enderio:block_electric_light:0" />
  <alias name="LIGHT_ELECTRIC_INV" item="enderio:block_electric_light:1" />
  <alias name="LIGHT_BASIC" item="enderio:block_electric_light:2" />
  <alias name="LIGHT_BASIC_INV" item="enderio:block_electric_light:3" />
  <alias name="LIGHT_WIRELESS" item="enderio:block_electric_light:4" />
  <alias name="LIGHT_WIRELESS_INV" item="enderio:block_electric_light:5" />

  <alias name="PPP_WOOD" item="enderio:block_painted_pressure_plate:0" />
  <alias name="PPP_STONE" item="enderio:block_painted_pressure_plate:2" />
  <alias name="PPP_IRON" item="enderio:block_painted_pressure_plate:4" />
  <alias name="PPP_GOLD" item="enderio:block_painted_pressure_plate:6" />
  <alias name="PPP_DARK_STEEL" item="enderio:block_painted_pressure_plate:8" />
  <alias name="PPP_SOULARIUM" item="enderio:block_painted_pressure_plate:10" />
  <alias name="PPP_TUNED" item="enderio:block_painted_pressure_plate:12" />

  <alias name="PPP_WOOD_SILENT" item="enderio:block_painted_pressure_plate:1" />
  <alias name="PPP_STONE_SILENT" item="enderio:block_painted_pressure_plate:3" />
  <alias name="PPP_IRON_SILENT" item="enderio:block_painted_pressure_plate:5" />
  <alias name="PPP_GOLD_SILENT" item="enderio:block_painted_pressure_plate:7" />
  <alias name="PPP_DARK_STEEL_SILENT" item="enderio:block_painted_pressure_plate:9" />
  <alias name="PPP_SOULARIUM_SILENT" item="enderio:block_painted_pressure_plate:11" />
  <alias name="PPP_TUNED_SILENT" item="enderio:block_painted_pressure_plate:13" />

  <alias name="ADVANCED_FILTER" item="enderio:item_item_filter:1" />
  <alias name="COUNTING_FILTER" item="enderio:item_item_filter:2" />

</enderio:recipes>

=== 01QueN10/EnderIO/resources/assets/enderio/config/recipe_base_core.xml
<?xml version="1.0" encoding="UTF-8"?>
<enderio:recipes xmlns:enderio="http://enderio.com/recipes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://enderio.com/recipes recipes.xsd ">

<!-- 

These are the build-in recipes. You cannot change this file, it is a
reference for you only and will be generated every time the game starts.

To make changes to the recipes, copy the recipes you want to change to
the matching _user.xml. To disabled a recipe, add an attribute "disabled"
and set it to true, e.g.: <recipe name="Gear" disabled="true" />

Item specifications can reference an alias, an ore dictionary name, a
block or an item. You can force the type by prefixing the value with
"oredict:", "block:" or "item:". Recipes that have items that cannot be
found in-game are either skipped or an error, depending on their "required"
attribute.

More information on the syntax can be found in the recipes.xsd file. An
XML editor will display that as tooltips when editing this file.

 -->

  <recipe name="Painted Pressure Plate, Dark Steel" required="true">
    <crafting>
      <grid size="2x1">
        <item name="DARK_STEEL" /><item name="DARK_STEEL" />
      </grid>
      <output name="PPP_DARK_STEEL" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Soularium" required="true">
    <crafting>
      <grid size="2x1">
        <item name="SOULARIUM" /><item name="SOULARIUM" />
      </grid>
      <output name="PPP_SOULARIUM" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Wood, Silent" required="true">
    <crafting>
      <grid size="1x2">
        <item name="minecraft:wooden_pressure_plate" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_WOOD_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Stone, Silent" required="true">
    <crafting>
      <grid size="1x2">
        <item name="minecraft:stone_pressure_plate" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_STONE_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Iron Silent" required="true">
    <crafting>
      <grid size="1x2">
        <item name="minecraft:heavy_weighted_pressure_plate" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_IRON_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Gold Silent" required="true">
    <crafting>
      <grid size="1x2">
        <item name="minecraft:light_weighted_pressure_plate" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_GOLD_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Wood, Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_WOOD" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_WOOD_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Stone, Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_STONE" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_STONE_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Iron Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_IRON" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_IRON_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Gold Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_GOLD" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_GOLD_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Dark Steel Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_DARK_STEEL" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_DARK_STEEL_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Soularium Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_SOULARIUM" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_SOULARIUM_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Painted Pressure Plate, Tuned Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="PPP_TUNED" />
        <item name="minecraft:wool" />
      </grid>
      <output name="PPP_TUNED_SILENT" />
    </crafting>
  </recipe>

  <recipe name="Exit Rail" required="true">
    <crafting>
      <grid size="3x3">
        <item name="ingotIron" /><item name="minecraft:piston" /><item name="ingotIron" />
        <item name="ingotIron" /><item name="minecraft:stone_pressure_plate" /><item name="ingotIron" />
        <item name="ingotIron" /><item name="dustRedstone" /><item name="ingotIron" />
      </grid>
      <output name="enderio:block_exit_rail" amount="6" />
    </crafting>
  </recipe>

  <recipe name="Detector Block" required="true">
    <crafting>
      <grid size="3x3">
        <item name="itemChassiParts" /><item name="PPP_DARK_STEEL" /><item name="itemChassiParts" />
        <item name="itemChassiParts" /><item name="piston" /><item name="itemChassiParts" />
        <item name="itemChassiParts" /><item name="redstone_block" /><item name="itemChassiParts" />
      </grid>
      <output name="enderio:block_detector_block" />
    </crafting>
  </recipe>

  <recipe name="Detector Block, Silent" required="true">
    <crafting>
      <grid size="3x3">
        <item name="itemChassiParts" /><item name="PPP_DARK_STEEL_SILENT" /><item name="itemChassiParts" />
        <item name="itemChassiParts" /><item name="piston" /><item name="itemChassiParts" />
        <item name="itemChassiParts" /><item name="redstone_block" /><item name="itemChassiParts" />
      </grid>
      <output name="enderio:block_detector_block_silent" />
    </crafting>
  </recipe>

  <recipe name="Detector Block, Silent, Upgrade" required="true">
    <crafting upgrade="true">
      <grid size="1x2">
        <item name="enderio:block_detector_block" />
        <item name="minecraft:wool" />
      </grid>
      <output name="enderio:block_detector_block_silent" />
    </crafting>
  </recipe>

</enderio:recipes>
